export const definitions = {
    a: "put this in front of a word to talk about just one of something (when you do not know which one of that thing)",
    able: "can do it - you can act without a problem - if you attempt a thing you will do it",
    about: "when a word or so can tell you what a thing is, or what a thing is like, the word or so is about that thing",
    above: "one thing is above another thing when you can go up from the first thing to get to the second",
    accept: "when you decide you are happy that something is - or at least you are not angry that something is",
    across: "",
    act: "pretend to be someone or something you are not - or - do a thing",
    actually: "when something is real and is some way",
    add: "put one thing and one other thing together",
    admit: "agree that a thing is right - or - take a person in to a place",
    afraid: "feel a scare about of something - to feel fear - to think something bad might happen",
    after: "when you are more old than you are now",
    afternoon: "late in the day when the sun is under the top of the sky",
    again: "to do the same thing that was done before",
    against: "to be on the other team to someone or something - or - to be next to something and press on it",
    age: "how old you are - how many a time you have seen the sun go up and down three hundred a time or so",
    ago: "in the past",
    agree: "say that the thing is right - say you are on the same side as the person who did say the thing",
    ah: "breathe out in a sigh, maybe because you are sad or maybe because you are afraid, or maybe because you feel relax",
    ahead: "to be further along a race (or something like a race) than someone",
    air: "the thing you breathe to live - usually very light and see-through - what you need to burn a thing",
    all: "everything - nothing is left out - every one of something is in here",
    allow: "let someone (or something) do something - not to stop something",
    almost: "get most of the way there but not quite all of the way there",
    alone: "just you and no other person - by yourself",
    along: "in a line from a place - or - when you move in a direction",
    already: "to have been before",
    alright: "a thing you say when you agree with what was said - or - when something is a bit good",
    also: "as well as - a word you use when you want to say both one thing and some other thing",
    although: "",
    always: "at every time - when a thing is never not this way",
    am: "",
    amaze: "to surprise someone with something that is very not normal",
    an: "like a, but for if the word has a different start",
    and: "as well - both this thing as well as that thing",
    anger: "feel in a strong way that the thing is bad, and maybe want to hurt or attack someone because of that",
    angry: "this person does feel anger",
    animal: "an thing that has life that can breathe and move and feel",
    annoy: "make someone a bit angry",
    another: "a second thing that is like the first one in some way",
    answer: `the reply to a question - the thing that a person who said a question will want to know - you might know that it is right, or it might be a guess and might be wrong - if it is a short answer it will be "yes", "no" or "maybe"`,
    any: "one of a thing - it might be one of them or it might be a different one",
    anymore: "for any more time or any more of a thing",
    anyone: "any person",
    anything: "any thing",
    anyway: "in any way a thing can be - or - what you say when you want to ignore what you did say",
    apartment: "a small place where you can live - often a type of home",
    apparently: "",
    appear: "how something can look - or - when you start to be able to see something",
    approach: "to come close to something",
    are: "how a thing is - like is",
    area: "how much of a place there is - the area is more big if it is more far from the left to the right of it when you stand in it and look any way",
    "aren't": `short for "are not"`,
    arm: "the bit of your body under the neck that is out to the left and the right (there is one of them on each side)",
    around: "to turn so your eye is where your back hair was - or - to be on every side of something",
    arrive: "to get where you want to go (after you move to there)",
    as: "a word to say one thing is like another thing",
    ask: "to say a question",
    asleep: "you when you lie in bed and can not see or hear for a while",
    ass: "an animal like a horse but more slow",
    at: "in a place",
    attack: "try and hurt someone or something with force",
    attempt: "try to do something, maybe it does work and maybe it does not",
    attention: "focus - think only about one thing",
    aunt: "the sister of your dad, or the sister of your mum",
    avoid: "to stay away from someone or something",
    away: "not in a place",
    baby: "a very young person - a person who has an age less than two or so - a person that will cry even if they don't hurt",
    back: "the side of you that does not have an eye in it - or - to return in that direction",
    bad: "not good - a thing that does not do what it is meant to do, or a thing that can make people sad - worse than nothing at all",
    bag: "a soft round thing that you wear on your back or your side that you use to put stuff in",
    ball: "a round thing that is a bit soft - it can hit something and go on the other way",
    band: "a group of people that make music together - or - a round thing that can go tight and hold stuff together",
    bar: "a long hard round thing - or - a place you can go to get a drink that is not water",
    barely: "when something is a way, and if anything was a little different it would not be that way",
    bathroom: "a room in your house which you use to clean yourself - when you are in here you put water on your body",
    be: "how you are but tomorrow",
    beat: "when you were more quick than everyone in a race, you did beat every other person in the race - or - to hit something a lot",
    beautiful: `a thing you like to look at - a thing that can make you say "wow" when you look at it`,
    became: "",
    because: "why a thing is the way it is",
    become: "when you were a thing, or a way, and you change to be a different thing or way",
    bed: "a thing that you sleep on in the night",
    bedroom: "a room in your home that you sleep in - a room with a bed in it",
    been: "how a thing was",
    before: "a time that was - you must have been before, but you can't be before again and you never will be before",
    began: "when a thing did become a thing for the first time is when it began",
    begin: `to make a thing a thing for the first time - like "began" but now`,
    behind: "the area near you that you can't see is behind you",
    believe: "when you think a thing is right - maybe it is or maybe it isn't",
    bell: "a hard, half round, half open thing that you can hit to make a nice sound",
    beside: "",
    besides: "",
    best: "when one of a thing is more good than every other one of that thing",
    better: "when one thing is more good than another thing",
    between: "a thing with one thing on one side and another thing on the other side is between them",
    big: "large - not small - when some of something is a long way a way from some other bit of that same thing",
    bit: "when you did bite someone in the past",
    bite: "to push on a thing with your top teeth and your bottom teeth - often so you can eat it",
    black: "the color that you have when you have no color - the color of the sky but with no night sky ball or star",
    blink: "to close both your left eye and right eye at the same time - often to make them a bit wet so they can work",
    block: "a large thing that is not round - or - to stop a person so they can't do the thing they want to do",
    blonde: "the color of some hair - a bit like the color of the sun",
    blood: "the red thing that is like water that is in your body to keep death away - when you lose more than a bit of this you should see a doctor - to see this can make someone afraid",
    blue: "the color of the sky when it is bright - the color of water when there is a lot of it",
    blush: "",
    body: "the thing you are, or are in - your arm, your neck, your head, your leg, each finger, your shoulder - they are all a part of your body",
    book: "a box with many a word in it - it might help you know something, or it might be a fun story about a not real thing",
    bore: "",
    both: "a word for when you have one thing and you also have another thing - like and",
    bother: "",
    bottle: "a box you put water or a thing like it in - often made of glass",
    bottom: "the bit of a thing that is under the rest of it",
    box: "a thing that is empty inside, that you put stuff inside to carry or store",
    boy: "a man who is young",
    boyfriend: "a boy (or young man) who is your friend - maybe who you kiss and think is beautiful or even go to bed with",
    brain: "the thing in your head that you use to think",
    break: "when you hit or cut a thing so that a bit of it is not with the rest of it anymore",
    breakfast: "food you eat at the start of the day",
    breath: "the air you pull and push out of your mouth to live",
    breathe: "when you push and pull air in and out of your body through your mouth, so that you can live",
    bright: "when there is a lot of light - the sun is bright, the night sky ball is less bright",
    bring: "take a thing to a place",
    broke: "when you had hit or cut a thing so that a bit of it is not with the rest of it anymore",
    broken: "when a thing is no what it should be - or when a thing that was one is now more than one",
    brother: "a man who has the same mum and dad as you",
    brought: "",
    brown: "the color of the world if you break the top off - or of shit",
    brush: "",
    build: "",
    burn: "set something on fire - make something so hot that it can stay hot on it's own - almost always will make smoke",
    burst: "when something is so full that it is cut into more than one piece by the stuff inside it",
    bus: "a big car that can fit more than ten people - often in the city you will ride one to work",
    business: "",
    busy: "when you have to do a lot in a small bit of time - maybe you have a lot of work to do, or a lot of people to talk to, in a small bit of time",
    but: "a word when you want to say one thing and another thing, and the second thing will make the first thing mean something weird",
    buy: "give someone money so that something they did own is now something you own - give some money and get a thing",
    by: "a word to say what or who did a thing - or - to move next to something",
    call: "yell or use a phone to talk to someone, maybe to ask them to come to where you are",
    calm: "",
    came: "",
    can: "when you are able to do a thing - or - a box you put food in that is very tight and hard",
    "can't": `short for "can not" (there's actually another way to make that short, but I can't write it with what I can use here)`,
    car: "a box that four or so people can fit in, that can move you all very fast - often with a door on the front and back of the left and right side",
    card: "",
    care: "",
    carefully: "",
    carry: "hold a thing so that you can take it to a place that it is not",
    case: "an way a thing can happen - or - a type of box, often a small one for food or drink",
    cat: "an animal about as tall as your knee that has a long soft line from it's back, and four of a leg to stand on - more quiet and a bit more small than a dog",
    catch: "",
    caught: "",
    cause: "the thing that did make another thing be the way it is",
    cell: "",
    chair: "a piece of wood (or something like it) that you sit on - often you sit on it when you eat, or when you write",
    chance: "",
    change: "to not be the way you were anymore",
    chase: "",
    check: "make sure that you are right about what you think you know - or, write something to agree that something is right - or - in a game when you and one other person move six and ten little not real people around each, move one of your people so that can't move their most important piece",
    cheek: "the soft side of your mouth - you have one the left and one on the right - or - the soft left and right side of the bit of you that you sit on - or - to say a joke that might make someone angry",
    chest: "the bit of your body that is under your neck - the bit that your heart is in - or - a big box you put stuff in",
    child: "a person who is not old - often if a man and a woman fuck, they can make a child",
    children: "more than one child",
    chuckle: "",
    city: "like a town but with a lot more of everything that isn't green",
    class: "",
    clean: "to not have any not nice stuff stuck to you - or - to take the not nice stuff off something, often with water",
    clear: "take all of a thing away from a place",
    climb: "",
    close: "make a thing not open",
    clothes: "like a bag you wear over your body - often your foot, or your chest, or your bottom and both your left and right leg - if it is cold maybe each arm as well as your chest, or your head",
    coffee: "something you can drink to wake up that will smell like a warm fire to your nose but feel like wet ground in your mouth",
    cold: "not hot - maybe when the sun is down and it can make your skin feel not good - very cool",
    college: "like a school but for people who are done with school and want to know even more",
    color: "how a thing can look - might be red or blue or green or grey",
    come: "when you go from one thing to another you did come to the second thing",
    comment: "",
    complete: "",
    completely: "",
    computer: "a box that can think what we tell it to",
    concern: "",
    confuse: "",
    consider: "",
    continue: "",
    control: "",
    conversation: "when a few people say a lot to each other for a while",
    cool: "almost cold - like when there is a bit of rain but not sky-ice - or - when a person has dark glass over their eye",
    corner: "where more than one side of a thing is - maybe the bit of a box that has a point, or the bit of a road that should make you turn the car",
    couch: "a big soft chair, often one you sit in to watch tv or read a book",
    could: "when you were (or are) able to do something (but maybe you didn't)",
    "couldn't": `short for "could not"`,
    counter: "",
    couple: "two of something - or - two people who like each other a lot and stay together a lot",
    course: "",
    cover: "to surround something - or, a thing that can surround another thing, so you can't see it from the outside or so you can't touch it from the outside - to wrap a whole thing - or, a thing that someone did use to cover another thing",
    crack: "",
    crazy: "",
    cross: "",
    crowd: "",
    cry: "when you push water out of your eye because you are sad - or - when you yell",
    cup: "a round and deep thing that you can put water, or something like water, in - often, you drink from this",
    cut: "use a hard not wide thing (like a weird rock, or a broken bit of glass) to break a thing in a clean way - or - the break when a hard not wide thing has gone through a bit of something",
    cute: "",
    dad: "a man who has made a child",
    damn: "",
    dance: "",
    dark: "when it is not light - when it is hard to see anything",
    date: "",
    daughter: "a child you made who is a girl is your daughter",
    day: "the time when the sun is in the sky - or - the time from the sun up start to another sun up start - there are seven of these in a week",
    dead: "when a thing can not move or breathe or think or feel anymore - when a thing is not a live thing anymore",
    deal: "",
    dear: "",
    death: "not life - what will make a thing that is live, dead",
    decide: "when you did not know what you would do or think, but now you do",
    deep: "a thing which is tall, but down instead of up - or - down a long way",
    definitely: "",
    desk: "a table you use to write, or work at, or put a computer on",
    did: "when you had made some act in the past",
    "didn't": `short for "did not"`,
    die: "",
    different: "not the same as something",
    dinner: "a thing you eat at the end of the day when it is almost dark",
    direction: "a way you can point your nose",
    disappear: "",
    do: "act in some way",
    doctor: "a person who can often make a sick person not sick - or, a person who should understand a lot because they did a lot of school",
    does: "act in some way",
    "doesn't": `short for "does not"`,
    dog: "an animal about as tall as your knee that has a long soft line from it's back, and four of a leg to stand on - more loud and strong than a cat",
    "don't": `short for "do not"`,
    done: "when you did act in some way in the past",
    door: "an empty part of a wall with a bit of wood in it that you can turn open or shut, there to allow you to walk through the wall",
    doubt: "",
    down: "the direction from your head to your feet - very often, the direction the world is from you",
    drag: "",
    draw: "",
    dream: "",
    dress: "put a thing or two you wear on someone (often yourself) - or - a long and soft thing you can wear, often if you are a woman",
    drink: "put a thing like water or coffee in your body through your mouth so that you can live - or - a thing like water (often water) that you put in your body so you can live ",
    drive: "use a car or a bus to go from one place to another",
    drop: "",
    drove: "",
    dry: "make something not wet",
    during: "",
    each: "when a thing is about every one of a thing",
    ear: "",
    early: "",
    easily: "",
    easy: "when a thing can be done and it does not tire you - not hard",
    eat: "put food in your mouth, bite it and pull it into your stomach",
    edge: "",
    either: "one of two of a thing",
    else: "if this thing is not the case - or - as well as",
    empty: "not full - when a thing doesn't have any other thing in it",
    end: "when a thing that was is not anymore - or - the last bit of a thing",
    enjoy: "do a thing or feel a thing in a way that does make you happy",
    enough: "the number of a thing that is the number that you need, but no more",
    enter: "go inside a place",
    entire: "all of a thing",
    escape: "leave a place that is hard to leave",
    especially: "",
    even: "when a number is two add two add two and so on - or - when more than one thing can all do the same thing as each other",
    evening: "",
    eventually: "",
    ever: "",
    every: "all of a thing",
    everyone: "every person",
    everything: "every thing",
    exactly: "",
    except: "like but - or - when all of a thing but one or so of that thing are a way",
    excite: "",
    exclaim: "make a loud sound that may or may not be a word",
    excuse: "",
    expect: "",
    explain: "",
    expression: "",
    eye: "a part of your body that you see out of - round and soft and in your head",
    eyebrow: "",
    face: "the bit of your head that has your nose - the bit of your head that you see from",
    fact: "",
    fall: "move down, at first slowly and then fast and then more fast - maybe because you did step off a tall thing, or maybe because you took a step wrong",
    family: "",
    far: "a place or thing that is a long way away from here - a place it will take a long time to get to",
    fast: "move from here to there in not much time",
    father: "the man who who did fuck your mum to make you",
    fault: "",
    favorite: "",
    fear: "when you worry that a bad thing will happen - when you don't want a bad thing to happen but you think it will",
    feel: "when you touch something and your brain does this",
    feet: "more than one foot",
    fell: "when you did fall - or - to cut down a tree - or - a very old, maybe angry thing, that should give you fear",
    felt: "when you did feel something - or - the soft skin with hair you can get from some kind of animal",
    few: "more than one of something - less than a lot of something",
    field: "",
    fight: "when people hit or yell at or bite or kill each other, often because they are angry at each other",
    figure: "think until you know a thing - or - a little thing that is made to look the same as a big thing",
    fill: "",
    finally: "",
    find: "",
    fine: "very nice and very pretty - or - when you have to pay money because you did a bad thing",
    finger: "you have five of these on each hand - they are round and small and are made of three of a more small thing, except for the inside one which is made of two of a more small thing",
    finish: "",
    fire: "very very hot air that will break wood or something like it to keep hot",
    first: "one of a thing that is ahead (or before) of all the other of that thing",
    fit: "when you can put a thing inside another thing and you don't need to push too hard - or - when you can run very far and not tire",
    five: "a number - one and one and one and one and one - or - three and two",
    fix: "make a thing that did break whole again",
    flash: "a quick bright light",
    flip: "turn a thing around so that it's back is now it's front, or it's top is now it's bottom",
    floor: "",
    fly: "move through the air and not fall - or - a tiny animal that can do this",
    focus: "look very hard at or think very hard about something so you can pay full attention to it",
    follow: "go the same way as a person that went a way before you",
    food: "something you put in your mouth, break with your teeth, then pull into your body with your throat to live",
    foot: "there should be one of these at the bottom of each leg - they go forward and back so you can walk - they are long while you stand and can be a bit tall while you are in bed, and they are what you should put a shoe on",
    for: "the place a person will go - or - the person that should get a thing",
    force: "push a thing until it does what you want it to - or - a push or pull",
    forget: "when you did know a thing but now you do not",
    form: "",
    forward: "to move in the direction of your nose",
    found: "",
    four: "two and another two",
    free: "when you are able to do what you want to do - or - when you can take something with no money",
    friend: "a person you like to be with - you might go to their house or they might come to your house",
    from: "a place that you were before you did move",
    front: "the side that the face of a person is on - or, the direction that the face of a person or thing is from them",
    frown: "when your mouth is sad and each end of it is under the middle of it",
    fuck: "when you and a person you love put your whole body together (often in bed) - or - a not nice word you say when you feel bad or sad (like shit)",
    full: "when a cup has all water and no air in it",
    fun: "the way you feel when you play, or go to a party, or have a game",
    funny: "when a thing is weird but fun in a way that can make you laugh or smirk - or - when a thing is weird",
    further: "more far away",
    game: "",
    gasp: "",
    gave: "",
    gaze: "look at something and don't look away",
    gently: "touch something in a very slow and not hard way - or, say something in a quiet and kind way",
    get: "take a thing - or have someone give you a thing",
    giggle: "laugh in a soft and quiet way",
    girl: "a woman who is young",
    girlfriend: "a woman you you like to spend time with (maybe in bed)",
    give: "put your thing with someone else so they can have it",
    given: "",
    glad: "when you are happy because of the way a thing is - when you like the way a thing is very much",
    glance: "to look at something for a short time",
    glare: "to look at something with anger",
    glass: "a hard thing you can see through that is easy to break",
    go: "to move from one place to another place",
    god: "a person who can do more than any other person",
    gone: "to not be in the place anymore, and be in another place instead",
    gonna: "",
    good: "a thing that is the way it should be - a thing that is the way you want it to be",
    got: "",
    gotten: "",
    grab: "",
    great: "",
    green: "the color of the small soft ground that does grow",
    greet: `to say to someone "hello, I'm glad to see you", or something like that`,
    grey: "a sort of color that is a bit of every color, but they make each other not color - the color of a dark soft sky rain cup",
    grin: "when your mouth is happy and each end of it is above the middle of it - like smile, but often when something is funny",
    grip: "",
    groan: "to exclaim with a deep, not very loud sound, often because you are sad or almost asleep",
    ground: "the top of the world - the thing that you stand on - or - to be a cause or reason for something",
    group: "more than one of a thing, together",
    grow: "to go from small to less small as you get more old",
    guard: "a person who will try to keep something safe - or - to try to keep something safe",
    guess: "when you try to answer a question, but you are not sure that your answer is right",
    gun: "a thing you hold that can throw a small, very hard thing very very fast out the end - often to hurt or kill someone",
    guy: "a man",
    had: "when you did have a thing",
    "hadn't": `short for "had not"`,
    hair: "the soft and a bit long and very not wide stuff that does grow on your head - often black, blonde, red or brown",
    half: "for every two of a thing, take one of it",
    hall: "",
    hallway: "",
    hand: "there should be one of these at the end of each arm - you can use them to hold a thing, or to punch a thing, or to wave",
    handle: "",
    hang: "",
    happen: "the way a thing did be",
    happy: "when you feel good because of the way a thing is - when you like the way the world is",
    hard: "not soft - if you punch it, you will be hurt",
    has: `own or hold or be with a thing - like "have"`,
    hate: "",
    have: `own or hold or be with a thing - like "has"`,
    "haven't": `short for "have not"`,
    he: "a word for a man when you know which man you talk about",
    "he'd": `short for "he would" or "he had"`,
    "he's": `short for "he is"`,
    head: "the round thing on top of your neck - what your brain is in and your mouth is on",
    hear: "when there is a sound and you feel it",
    heard: "when you did hear something",
    heart: "a thing in your chest that does push red water through your body so you can live",
    heavy: "when a thing is hard to pick up - when to hold a thing will tire your arm",
    held: "",
    hell: "",
    hello: `a word you use to greet someone - you can say it to answer another "hello" or a "hi" or a "hey"`,
    help: "do something so that someone else will be happy or well",
    her: "a word for a woman when you know which woman",
    here: "the place you are in now - the part of the world that you are in",
    herself: "",
    hey: `like "hi" or "hello"`,
    hi: `short for "hello"`,
    hide: "put a thing in a place where no other person can see it",
    high: "in a place that is a long way above the ground",
    him: "a word for a man when you know which man",
    himself: "",
    his: "a thing that the man this is about can own, or the thing that can own this man - or the person who is this to this man - his baby is the baby he did make, his mum is the woman who did make him",
    hit: "push a thing or a person with a part of your body",
    hold: "carry a thing in your hand",
    home: "where you live, often with the person you love in bed, or your father or mother or child - might be an apartment or a house - will often have a bedroom, a bathroom, and so on in it",
    hope: "to want a thing to happen",
    horse: "a large animal with four of a leg - one that a person can ride",
    hospital: "a place where many a doctor is - a place for many a sick person to go to to try and get not sick",
    hot: "when a thing can burn you - not cold",
    hour: "a bit of time - there are twenty and four of these in a day",
    house: "a type of home - a place that has a wall on each side",
    how: "",
    however: "",
    hug: "to hold someone with your arm to say you love them",
    huge: "very large",
    huh: "",
    human: "the animal that you are - an animal that can read and write",
    hundred: "a number - ten of ten",
    hung: "",
    hurry: "",
    hurt: "hit or burn or bite a person to make them sad - or - when a bit of you has been hit or so on and it does feel bad",
    i: "the person who did did use this word",
    "i'd": `short for "I had" or "I should" or "I would"`,
    "i'll": `short for "I will"`,
    "i'm": `short for "I am"`,
    "i've": `short for "I have"`,
    ice: "water that is so cold it is hard",
    idea: "",
    if: "",
    ignore: "",
    imagine: "",
    immediately: "",
    important: "",
    in: `short for "inside"`,
    inside: "when a thing does surround you, you are inside it - often, when you have a wall on every side of you",
    instead: "",
    interest: "",
    interrupt: "",
    into: "to move from the outside of a thing to the inside of a thing - maybe to put water into a cup, or food into your stomach, or yourself into your jacket",
    is: "",
    "isn't": `short for "is not"`,
    it: "",
    "it's": `short for "it is" or "it has" (not the same as "its")`,
    its: "",
    jacket: "something you wear over your chest and each arm to keep you warm when you feel cold",
    jeans: "",
    jerk: "",
    job: "",
    join: "",
    joke: "when you say a word or so that is funny - often will make a person laugh",
    jump: "",
    just: "",
    keep: "",
    kept: "",
    key: "a small thing you hold and put in a door to open it",
    kick: "use your foot to push something (maybe a ball) hard and fast",
    kid: "a person who is not old - or - to say something that is a joke",
    kill: "make an animal not live",
    kind: `very nice, will thank you a lot and accept you, and not forget you - or - the type of thing something is`,
    kiss: "touch your mouth against a bit of the body of another person (maybe their mouth) to say you love them",
    kitchen: "a room in a house that you use to make food",
    knee: "a wide hard bit in the middle of your leg that can let your foot move more or less close to your bottom - if you are shot here, it will mean you can't see stuff that can make you wonder as much anymore",
    knew: "",
    knock: "",
    know: "when you trust a thing is the truth and it is the truth",
    known: "",
    lady: "",
    land: "",
    large: "big - there is more of a large thing than there is of a small thing",
    last: "",
    late: "",
    laugh: "breathe out in a way that will make noise, because you are happy or because something was funny",
    lay: "",
    lead: "",
    lean: "",
    learn: "to begin to understand a thing - maybe because you repeat it, maybe because you study it at school or a college",
    least: "",
    leave: "",
    led: "",
    left: "the side of you that most people do not use to write",
    leg: "there should be two of these in the bottom half of you - they go forward and back so you can walk - they are tall while you stand and are long while you are in bed",
    less: "",
    let: "",
    letter: "",
    lie: "say something to try and make someone believe something that isn't the truth",
    life: "",
    lift: "",
    light: "a very tiny very very fast thing that can hit something and go into your eye to let you see it - or - when it easy to see everything (or hard because there it is so easy to see that you have to close your eye)",
    like: "",
    line: "",
    lip: "",
    listen: "",
    little: "",
    live: "",
    lock: "",
    locker: "",
    long: "",
    look: "",
    lose: "",
    lost: "",
    lot: "",
    loud: "when there is so much noise it might hurt your ear - if he's a loud one, he'd yell a lot",
    love: "when you like a thing, or person, very much - when you feel that to make that person happy is enough for you - when you feel like that thing is your entire world",
    low: "",
    lunch: "when you eat food in the middle of the day",
    mad: "when you don't like the way a thing or person is - it might annoy you, but this is more bad - you might frown or glare or try to kick something",
    made: "",
    make: "",
    man: "a type of human that often has short hair and often does not have a round chest",
    manage: "",
    many: "",
    mark: "",
    marry: "",
    match: "",
    matter: "",
    may: "",
    maybe: "",
    me: "the person who does now write this word - that is, I",
    mean: "",
    meant: "",
    meet: "",
    memory: "",
    men: "a group of more than one man",
    mention: "",
    met: "",
    middle: "",
    might: "",
    mind: "",
    mine: `when you did buy a thing, and now you can say of it "I have thing thing, and I'll keep it" - often, you'll often say "it isn't for you, because I've got it for me"`,
    minute: "a bit of time that is more than a second and less than an hour - there are three of twenty of these in an hour",
    mirror: "a glass that you can look into to see what's behind you - often there is one in your bedroom or bathroom that you use to check your hair in the morning",
    miss: "when you try to hit something, but you don't - or - when you wish a thing was still the way it was, or wish a person that is gone was still with you",
    mom: `short for "mother" - a different word for mum (if you are from a place that can write a word wrong)`,
    moment: "",
    money: "something you can use to buy something, maybe a tv or a couch or food or a house - often hard and bright",
    month: "three of ten of a day, give or take a few - about as long as it is from a full night sky light to an empty night sky light to a full night sky light",
    mood: "",
    more: "",
    morning: "the time of day when the sun is first in the sky",
    most: "",
    mother: "your mother is the woman who did make you",
    mouth: "what you use to smile, or breathe, or eat - the thing in your head that you can open and close",
    move: "go from one spot to another - maybe fast or maybe slow",
    movie: "one picture after another after another so fast they seem to move - maybe about food that can fight, or a mirror and a mean woman and a beautiful woman",
    "mr": "how you talk about a man when you are very nice and maybe do not know them very well",
    "mrs": "how you talk about a woman when you are very nice and maybe do not know them very well",
    much: "",
    mum: `short for "mother" - a different word for mom (if you are from a place that can write a word write)`,
    mumble: "talk in a quiet way that is hard to understand, often because you are sad or feel nervous to talk to people",
    music: "one sound after another in a way that is nice to hear - often made to go with a song",
    must: "",
    mutter: "talk in a quiet and quick way that is hard to understand, often because you are mad",
    my: "",
    myself: "",
    name: "",
    near: "",
    nearly: "",
    neck: "",
    need: "",
    nervous: "how you feel if you are about to ask someone you like if they would be in a relationship with you as your boyfriend or girlfriend",
    never: "at no time - if something hadn't ever been, and couldn't ever be, then it could never be",
    new: "",
    next: "",
    nice: "",
    night: "the time when the sun is not in the sky and it is dark - often the less bright white ball is in the sky instead - often everyone is asleep",
    no: "",
    nod: "",
    noise: `a sound of some sort - often not music - maybe a giggle or the voice of a horse or an "ah" or a conversation`,
    none: "",
    normal: "",
    nose: "",
    not: "",
    note: "",
    nothing: "no thing - without anything - an empty space, or not even the space",
    notice: "see something and pay attention to it",
    now: "the time it is as you read this",
    number: `a word that can tell you how many of a thing there are - the first number is "one", the next is "two", the third is "three", and so on.`,
    obviously: "",
    of: "",
    off: "",
    offer: "",
    office: "a place where a lot of people work, often at a desk with some coffee",
    often: "",
    oh: "",
    okay: "",
    old: "",
    on: "",
    once: "",
    one: "",
    only: "",
    onto: "",
    open: "",
    or: "",
    order: "",
    other: "",
    our: "",
    out: "",
    outside: "not inside - on the other side of the window to someone at work in an office or food in a kitchen - where wind is",
    over: "",
    own: "",
    pack: "",
    pain: "to feel like something hit you and it wasn't good - maybe because a shove and a trip broke the skin on your cheek",
    paint: "",
    pair: "",
    pants: "",
    paper: "when you break and wet a tree into something very not thick, you get this white thing you can write on",
    parents: "",
    park: "",
    part: "",
    party: "when some a group of people meet so they can have fun together - a party for a kid will often be because they are another year old, a party for men and women will often be so they can eat and drink and listen to music",
    pass: "",
    past: "",
    pause: "",
    pay: "",
    people: "a group of more than one person",
    perfect: "",
    perhaps: "",
    person: "an animal that does live and can both think and feel",
    phone: "something you can use to talk to someone (without a shout) who is too far away to talk to without a phone - not so long ago, they were a box in your house, but now they're more often a computer in your clothes",
    pick: "",
    picture: "a thing you can look at to see something else - often made with a box that will flash and then put what it can see on paper",
    piece: "",
    pink: "",
    piss: "",
    place: "",
    plan: "",
    play: "",
    please: "",
    pocket: "",
    point: "",
    police: "",
    pop: "",
    position: "",
    possible: "maybe a thing is real, maybe it will be real, or maybe not - if we've heard something is the truth from someone, but we haven't got a reason to trust them, it's just possible it is the truth",
    power: "",
    practically: "",
    present: "",
    press: "push or pull more than one thing together",
    pretend: "act as though or talk as though something that's not real, is real",
    pretty: "",
    probably: "",
    problem: "something that is bad - something that can make you not able to do a thing you want to do",
    promise: "say that you will do a thing even if it is hard to do",
    pull: `bring a thing to you with a touch - like "suck"`,
    punch: "make your hand a ball and use it to push something (maybe a face) hard and fast",
    push: "make a thing go away from you with a touch",
    put: "",
    question: "a word (or more than one word) that is said so that the person you talk to will tell you what you want to know",
    quick: `like "fast" - when a thing does not take much time - if he's quick, most people won't be as fast as him`,
    quickly: "do something quick - so that you will be done soon",
    quiet: "when there is no noise, or only a very little bit of noise - maybe a whisper",
    quietly: "when you do something in a way that does not make any noise",
    quite: "",
    race: "when a lot of people go as fast as they can and see who is the most fast - if the two that are the most fast are as fast as each other, it is a tie, else the most fast will get a thing for free",
    rain: "little water that will move down from the sky and make the ground not dry",
    raise: "",
    ran: "",
    rang: "",
    rather: "",
    reach: "",
    read: "look at a word, maybe say it out loud or quietly in your head, and understand it - often, look at word after word and understand a whole story",
    ready: "",
    real: "when something is",
    realize: "",
    really: "",
    reason: "",
    recognize: "when you see something (or someone) and know what (or who) it is - when you remember a thing as you see it",
    red: "the color of blood, or of the ball that can grow on a tree that we most often talk about - a more dark pink",
    relationship: "when one person and another person do stuff together, they are in a relationship",
    relax: "to not do much because you want to feel happy",
    remain: "to stay in the same place, or to stay in the same way - to wait and not change for a long time",
    remember: "when you think about a thing you did learn in the past",
    remind: "when you are made to remember a thing",
    repeat: "when you do a thing, and do the same thing again",
    reply: "when you are told a word or so by someone and you say a word or so back to them - like respond",
    respond: "when you are told a word or so by someone and you say a word or so back to them - like reply",
    rest: "",
    return: "",
    ride: "sit on a thing so it can carry you somewhere - maybe a bus if you are in the city, or a horse or and ass if you aren't",
    right: "one side of you (the one that is not left) - or - the thing that is good, or the word or so that is the same as the thing it is about",
    ring: "",
    road: "",
    rock: "",
    roll: "",
    room: "",
    rose: "",
    round: "",
    rub: "",
    run: `like "walk", but much more fast, and with both feet off the ground - if you need to escape and you can't drive, a burst of a run is your best chance`,
    rush: "",
    sad: "",
    safe: "",
    said: "",
    same: "",
    sat: "",
    save: "",
    saw: "",
    say: "",
    scare: "when you've made someone afraid, or the first part of when you are afraid",
    school: "a place that a lot of young people learn at - often where they use a bell to tell the time",
    scream: "yell very loud because you got a scare or you are in trouble - maybe because there is someone who might use a gun on you or beat you",
    search: "",
    seat: "",
    second: "a short bit of time, though a little more you'd take to blink - there are three of twenty of these in a minute - or - when you have two of a thing, the one you got after the other one is the second one",
    see: "",
    seem: "",
    seen: "",
    self: "",
    send: "",
    sense: "",
    sent: "",
    serious: "",
    seriously: "",
    set: "",
    settle: "",
    seven: "a number - three and four",
    several: "",
    shadow: "a dark area made when a thing you can't see through is between a bright light and another thing",
    shake: "",
    share: "",
    she: "a word for a woman when you know which woman you talk about",
    "she'd": `short for "she had" or "she would"`,
    "she's": `short for "she is" or "she has"`,
    shift: "",
    shirt: "one of your clothes that you wear on your chest - when you dress, you should pull it over your head so it will hug your shoulder - you shouldn't pull it up over your leg",
    shit: "a brown and wet thing that you push from yourself - or - a not nice word you say when you feel bad or sad (like shit)",
    shock: "when you did not think something would happen but then it did - can feel like surprise but with more pain",
    shoe: "a soft thing you put on your foot to keep it away from the ground when you walk",
    shook: "",
    shop: "a place where you can buy a thing or so",
    short: "it is not very far from the bottom of a short thing to the top of a short thing",
    shot: "",
    should: "",
    shoulder: "the bit of your body where the arm should join with the rest of the body - you have one on your right and one on your left, above your arm and under your neck",
    "shouldn't": `short for "should not"`,
    shout: "say something in a very loud way, so everyone who is around can hear you",
    shove: "push someone or something",
    show: "",
    shower: "",
    shrug: "",
    shut: "",
    sick: "when you feel bad, maybe too hot or too cold, and need to see a doctor or go to a hospital so they can make you better",
    side: "",
    sigh: "like a groan, but often because you tire and not because you are angry - maybe because you admit a thing is truth but you don't like it",
    sight: "",
    sign: "",
    silence: "",
    silent: "",
    simply: "",
    since: "",
    single: "just one of something - or - a person who is not part of a couple, who does not have a boyfriend or wife",
    sir: "",
    sister: "a woman who has the same mum and dad as you",
    sit: "put your bottom on something and remain in that place",
    situation: "",
    six: "a number - three and three",
    skin: "",
    sky: "all the air above you when you are one the ground - it is black at night and blue in the day, and the sun should move around it",
    slam: "",
    sleep: "to close your left eye and your right eye and not think for a little while - if she's got a heavy head, a sleep should help",
    slightly: "",
    slip: "",
    slow: "not fast - when it will take a lot of time to move not very far",
    slowly: "not quickly - take a long time to do something that shouldn't take a long time",
    small: "when every bit of something is close to every other bit of it - not tall and not wide - not big",
    smell: "",
    smile: "when your mouth is happy and each end of it is above the middle of it - like grin, but often when something is nice",
    smirk: "smile in a weird way",
    smoke: "air that is a dark color made from fire - often can make you breathe out fast when you didn't mean to",
    snap: "",
    so: "",
    soft: "",
    softly: "",
    some: "",
    somehow: "",
    someone: "any one person - one guy or girl or uncle or aunt or mother or son, but you don't know which one",
    something: "a thing of some sort - it could be any thing, maybe a thought or maybe a thing you can touch",
    sometimes: "at some time or another",
    somewhere: "a place of some sort - it could be any place",
    son: "a child you made who is a boy is your son",
    song: "word after word, each word with a bit of music",
    soon: "a little bit of time after now - not quite already, but close",
    sorry: "",
    sort: "",
    sound: "a thing you can hear - might be music or a song, or a yell or a scream or a bit of talk or a mumble or a mutter",
    space: "what a place is before there is a thing in it - empty space is a place with nothing in it, and outside space is above the sky, with the world, the sun, every star, and every thing (except maybe God) in it",
    speak: "make a noise with your mouth that another person can understand as a word",
    spend: "",
    spent: "",
    spoke: "",
    spot: "",
    stair: "",
    stand: "make your head as far from the ground as possible while your feet touch the ground",
    star: "like the sun, but so far away they look very small - you can only see them at night",
    stare: "",
    start: "",
    state: "",
    stay: "",
    step: "",
    stick: "",
    still: "",
    stomach: "inside your body and under your chest, this is where breakfast, lunch, dinner or a sweet will go after you eat it and before it will move out your bottom",
    stood: "",
    stop: "after you move, don't move anymore - or, after you do a thing, do not do anything - or, a word to warn someone that you do not want them to do what they do",
    store: "",
    story: "word after word to make you think about what what is, or might be the case - maybe it is told to amaze, or so you enjoy it - someone might speak the story or read it",
    straight: "when you can go from one end of a thing to the other and not turn at all - maybe a line, or a bar - or - when you are a man and you only like to fuck women, or a woman and you only like to fuck men",
    strange: "",
    street: "",
    strong: "",
    struggle: "",
    stuck: "",
    student: "a person who is at school or college to learn",
    study: "try to understand a thing more - maybe with a book to remind us what it is",
    stuff: "",
    stupid: "",
    such: "",
    suck: "pull on, often with your mouth",
    sudden: "",
    suddenly: "",
    suggest: "",
    summer: "the one out of four part of the year when it is more hot, and each day is more long",
    sun: "the big bright ball that is the cause of light in the day - it does a run up and down the sky once a day, and it can give anything a shadow when it is up except for right at the middle of the day",
    suppose: "",
    sure: "when you know that a thing is some way",
    surprise: "when you did not think something would happen but then it did - can feel like shock but more soft",
    surround: "be on every side of something",
    sweet: "what you feel in your mouth when you bite a round red ball that can grow from a tree - or when eat an after dinner little bite",
    table: "a wide thing that, about half as tall as you, that does not live - you can eat food from it or write on top of it, and can put a cup on it",
    take: "get a thing that was mine and make it your thing",
    taken: "when a thing that was mine was got by you it was taken",
    talk: "when you say a word or so out loud so other people can hear and know what you want them to understand",
    tall: "from the bottom of a tall thing to the top of a tall thing is a long way",
    teacher: `a person who can tell other people about a thing or to - someone who can help other people understand a lot of stuff - often we'll call them "Mr" or "Miss"`,
    team: "a group of people who try to do something together - they might work together or race together",
    tear: "when you pull a thing in more than one direction to break it into more than one piece - or - a bit of water made by your eye when you're sad",
    teeth: "you should have a lot of them in your mouth - white and hard and maybe straight",
    tell: "talk to someone about something",
    ten: "the number of word in this word group is ten",
    than: "",
    thank: "tell someone you are happy because of what they did",
    that: "",
    "that's": `short for "that is"`,
    the: "put this in front of a word to talk about just one of something (when you know which one of that thing)",
    their: "",
    them: "two or more people that are not you or me - or - a person, if you do not want to call them a him or a her",
    themselves: "a group of more than one person, but just that group and no other people",
    then: "a time that was before now",
    there: "a word for a place that is somewhere you are not - or - a word to say that something is",
    "there's": `short for "there is"`,
    these: "",
    they: "two or more people (or more than one thing) that is not you or me - or - a person, if you do not want to call them a him or a her",
    "they'd": `short for "they did" or "they had"`,
    "they're": `short for "they are"`,
    thick: "",
    thing: "one of anything - often something you can touch - might be a ball, or a dog, or a cup, or a sun",
    think: "say word after word in your head - try and figure out something in your head",
    third: "the thing after the thing after the first thing - the thing after the second thing",
    this: "put this in front of a word to talk about just one of something (when you know which one of that thing and you are right at it)",
    those: "",
    though: "",
    thought: "",
    three: "one thing, and one more thing, and one more thing, but no more than that",
    threw: "when you had done a throw before",
    throat: "the thing above your body, under your head, and inside your neck - air will go through this when you breathe",
    through: "",
    throw: "use your arm to push something",
    tie: "wrap a soft and long thing so that it is stuck to it - or - a long and not wide thing you tie above your jacket to look nice, often if you are a man",
    tight: "when one thing is close to another thing and all around it - maybe, when it is hard to take off your shirt, or hard to take off a bottle top",
    time: "how anything can change - what is different between before and after - how anything did begin",
    tiny: "very small - maybe hard to see because it is so small - maybe a hair or the small thing that air is made of",
    tire: "make someone want to be asleep",
    to: "",
    today: "the day it is now, if the sun is in the sky - tomorrow, it will be tomorrow, but for now it is today",
    together: "when one thing and another thing are close to each other - when there is not much between one thing and another thing - or - when two people often kiss because they love each other",
    told: "when something was said in the past",
    tomorrow: "the day after today - the day it will be when the sun has been down and up again",
    tone: "the way a noise is - it might be bright or hard or high or low - a big car will often have a tone that is hard and low but a little animal that can fly will often have a tone that is high and bright",
    tongue: "",
    tonight: "the time it is now, if the sun is not in the sky - often, if you are in your bedroom it is tonight",
    too: "put this word after a thing and another thing when you want to say that they are both together",
    took: "when you have a thing that someone else had in the past, you took that thing",
    top: "the bit of a thing that is above everything else that is part of the thing (your hair is the top of your body)",
    totally: "",
    touch: "when one thing and another thing are next to each other with nothing between them they touch each other",
    toward: "when you move so that you become more close to me, you move toward me",
    town: "a lot more than one home all together",
    track: "a line on the ground that people can follow to get from one place to another - might be wide or not wide, might be made by a person or an animal - or - to follow someone or something",
    trail: "a line on the ground that people can follow to get from one place to another - like a track",
    train: "a big box made by people that can take many people from one place to another place - can only go on a long hard line next to another long hard line",
    tree: "a big brown tall thing with many of a little round not thick thing (often green) that grow off it",
    trip: "to go from one place to another place for a bit of time - or - when you walk, and then kick something and fall over a bit",
    trouble: "when there is a big chance that something bad will happen",
    trust: "when you think that someone will not break their promise",
    truth: "what is - when what is said is the same as what is",
    try: "when you want something to happen and you do a thing or two and hope that it will happen",
    turn: "when you point your body to where your left was before or where your right was before (or at least, a bit of the way there)",
    tv: "a box that can play a movie on it - often many a short movie that go together - maybe about ice and fire",
    twenty: "two of ten",
    two: "the number when you have one thing, and one other thing, but not any more than that",
    type: "write a thing with a computer - or - what group that are all like each other a thing is part of",
    uncle: "the brother of your dad, or the brother of your mum",
    under: "",
    understand: "when you know what a thing is about - when you know what someone has in their brain",
    until: "",
    up: "away from the ground - on the way to the sky",
    upon: "",
    us: "you and me (if we are together), and maybe other people with us",
    use: "",
    usual: "",
    usually: "",
    very: "",
    visit: "go somewhere for a little bit of time",
    voice: "when you talk to someone, the noise you make from your mouth is your voice",
    wait: "stop what you do until the thing you expect to happen does happen",
    wake: "do not sleep anymore - get out of bed and start to give attention to the world",
    walk: "move your left leg and then your right leg and then your left leg again to move your body slowly",
    wall: "some stuff put on top of other stuff to block one place from another - might be a tiny wall to keep a little green live thing safe, a more big wall to hold up a house, or a huge wall that I'd be able to see if I was in space, and they'd not be able to get around if they went very very far left or right",
    want: "",
    warm: "almost hot, but it should feel more nice - or, to make something more hot",
    warn: "tell someone that something bad is about to happen",
    was: "",
    "wasn't": `short for "was not"`,
    watch: "to look at something for a while - or - something you wear near your hand which can tell you what time of day it is",
    water: "the thing that can make something wet - clear and not hard and often see through - you must drink this to live - even more important than breakfast",
    wave: "a wall of water (or air) that will move in a direction for a while - or - to move your hand from left to right and back to left again (and so on) to say hello to someone",
    way: "a trail from one place to another place - or - how a thing is",
    we: "you and me and maybe some other people",
    "we'll": `short for "we will"`,
    "we're": `short for "we are"`,
    "we've": `short for "we have"`,
    wear: "when you put a soft thing on your body to cover your body (or a bit of it)",
    week: "seven of a day",
    weird: "not normal - different to most of something",
    well: "to be not sick - or - when something is (or was) the way you would like to be",
    went: "to have gone somewhere or some way in the past",
    were: "the have been some place or some way in the past",
    "weren't": `short for "were not"`,
    wet: "when something has water on it and it is not as hard anymore, and maybe not as hot either",
    what: "",
    "what's": `short for "what is"`,
    whatever: "",
    when: `a word you use to ask or say what time a thing is - you might ask "when she'd like to hear the band?" if you would like to know the time she would like to hear some music, to which the answer might be "Tonight" if she could barely wait`,
    where: `a word you use to ask which place a thing is about, or what place a thing is near - you might ask "where is my guard", if they aren't near you but you would like to find them, or "where is my daughter", if you're in the middle of a game of hide and find`,
    whether: "",
    which: "",
    while: "",
    whisper: "say something in a very very quiet way, so your breath is almost as loud as your word",
    white: "the color of the bright night sky ball, and the color of the thing everyone can write on if they have a small stick with a dark thing like water in it",
    who: `a word you use to ask which person a thing is about - you might ask "Doctor who?", to find out which doctor gave someone their new knee, or you might ask "Mrs. who?" to ask a child which teacher they have in their class, or "who is on that train" if you see someone wave to it but you don't recognize anyone on it`,
    whole: "",
    why: "a word you use to ask a question about the reason a thing is the way it is - often, a student will ask this to a teacher - children ask this a lot",
    wide: "",
    wife: "a woman you live with and should love very much - a woman you promise to go to bed with as long as you both live - a woman you kiss and fuck because you love each other",
    will: "",
    wind: "when air does move past the world - it can be cold or loud sometimes",
    window: "a thing you can look through to see the world outside when you are inside something",
    wipe: "push water or something like it gently off something else",
    wish: "ask for something to happen that you would like to happen",
    with: "when one thing and another thing are together, they are with each other",
    within: "inside - in between the left and the right and the top and the bottom of something",
    without: "outside - not within",
    woke: "when you made someone not asleep in the past",
    woman: "a type of human that often has long hair and a round chest",
    women: "a group of more than one woman",
    "won't": `short for "will not" (weird, isn't it) - wouldn't, or weren't, but now`,
    wonder: "to think about how a thing might be",
    wood: "the hard brown bit of a tree - you can use it to make a table, or a house, or something else",
    word: `a single bit of what you say or write that will still mean something when alone`,
    wore: "",
    work: "what you do to get money, often from the morning until the afternoon",
    world: "everything around you except for the far away sky",
    worry: "",
    worse: "when one thing is not as good as another thing it is worse",
    would: "",
    "wouldn't": `short for "would not"`,
    wow: "a sound you make when you fell surprise or shock",
    wrap: "cover something in something soft",
    write: "put a word or so onto a piece of paper or a computer",
    wrong: "when you say a word or so that is not the way that something is (that is, not right) - or, when you do something that is bad",
    yeah: `what you say when you think what was said is right, and you do not want to say "yes"`,
    year: "three of one hundred, six of ten, and five of one of a day - when the sun is quickly gone, slowly gone, and quickly gone again - when the world has gone around the sun once - the time from one summer to another - ten and two of a month",
    yell: `say something very loud and in a hard tone, maybe because you're angry - like "scream" but you may not feel fear and what you say may be a real word - like "exclaim"`,
    yes: `what you say when you think what was said is right, and you want to say something that is more sure than "yeah"`,
    yet: "",
    you: "the person who can see from your eye and feel from your hand - the person who right now can understand this word - the person who has the same mum and dad as you who is not your brother or sister - should be one of the people who is most often in your house",
    "you'd": `short for "you would"`,
    "you'll": `short for "you will"`,
    "you're": `short for "you are"`,
    "you've": `short for "you have"`,
    young: "when someone or something has not felt many of a year",
    your: `like "his" or "her" - a thing you own - your thing is a thing that you can use for what you want to use it for - or - the person or thing that is this to you`,
    yourself: "you - every bit of you",
}