export const definitions = {
    a: "put this in front of a word to talk about just one of something (when you do not know which one of that thing)",
    able: "can do it - you can act without a problem - if you attempt a thing you will do it",
    about: "when a word or so can tell you what a thing is, or what a thing is like, the word or so is about that thing",
    above: "one thing is above another thing when you can go up from the first thing to get to the second",
    accept: "when you decide you are happy that something is - or at least you are not angry that something is",
    across: "",
    act: "pretend to be someone or something you are not - or - do a thing",
    actually: "when something is real and is some way",
    add: "put one thing and one other thing together",
    admit: "agree that a thing is right - or - take a person in to a place",
    afraid: "feel a scare about of something - to feel fear - to think something bad might happen",
    after: "when you are more old than you are now",
    afternoon: "late in the day when the sun is under the top of the sky",
    again: "to do the same thing that was done before",
    against: "to be on the other team to someone or something - or - to be next to something and press on it",
    age: "how old you are - how many a time you have seen the sun go up and down three hundred a time or so",
    ago: "in the past",
    agree: "say that the thing is right - say you are on the same side as the person who did say the thing",
    ah: "breathe out in a sigh, maybe because you are sad or maybe because you are afraid, or maybe because you feel relax",
    ahead: "to be further along a race (or something like a race) than someone",
    air: "the thing you breathe to live - usually very light and see-through - what you need to burn a thing",
    all: "everything - nothing is left out - every one of something is in here",
    allow: "let someone (or something) do something - not to stop something",
    almost: "get most of the way there but not quite all of the way there",
    alone: "just you and no other person - by yourself",
    along: "",
    already: "to have been before",
    alright: "a thing you say when you agree with what was said - or - when something is a bit good",
    also: "as well as - a word you use when you want to say both one thing and some other thing",
    although: "",
    always: "at every time - when a thing is never not this way",
    am: "",
    amaze: "to surprise someone with something that is very not normal",
    an: "like a, but for if the word has a different start",
    and: "as well - both this thing as well as that thing",
    anger: "feel in a strong way that the thing is bad, and maybe want to hurt someone because of that",
    angry: "this person does feel anger",
    animal: "an thing that has life that can breathe and move and feel",
    annoy: "make someone a bit angry",
    another: "a second thing that is like the first one in some way",
    answer: "the reply to a question - the thing that a person who said a question will want to know",
    any: "one of a thing - it might be one of them or it might be a different one",
    anymore: "for any more time or any more of a thing",
    anyone: "any person",
    anything: "any thing",
    anyway: "in any way a thing can be - or - what you say when you want to ignore what you did say",
    apartment: "a small place where you can live - often a type of home",
    apparently: "",
    appear: "how something can look - or - when you start to be able to see something",
    approach: "to come close to something",
    are: "how a thing is - like is",
    area: "",
    "aren't": `short for "are not"`,
    arm: "the bit of your body under the neck that is out to the left and the right (there is one of them on each side)",
    around: "to turn so your eye is where your back hair was - or - to be on every side of something",
    arrive: "to get where you want to go (after you move to there)",
    as: "a word to say one thing is like another thing",
    ask: "to say a question",
    asleep: "you when you lie in bed and can not see or hear for a while",
    ass: "an animal like a horse but more slow",
    at: "in a place",
    attack: "try and hurt someone or something with force",
    attempt: "try to do something, maybe it does work and maybe it does not",
    attention: "focus - think only about one thing",
    aunt: "the sister of your dad, or the sister of your mum",
    avoid: "to stay away from someone or something",
    away: "not in a place",
    baby: "a very young person",
    back: "the side of you that does not have an eye in it - or - to return in that direction",
    bad: "not good - a thing that does not do what it is meant to do, or a thing that can make people sad",
    bag: "a soft round thing that you wear on your back or your side that you use to put stuff in",
    ball: "a round thing that is a bit soft - it can hit something and go on the other way",
    band: "a group of people that make music together - or - a round thing that can go tight and hold stuff together",
    bar: "a long hard round thing - or - a place you can go to get a drink that is not water",
    barely: "when something is a way, and if anything was a little different it would not be that way",
    bathroom: "a room in your house which you use to clean yourself - when you are in here you put water on your body",
    be: "how you are but tomorrow",
    beat: "when you were more quick than everyone in a race, you did beat every other person in the race - or - to hit something a lot",
    beautiful: "a thing you like to look at",
    became: "",
    because: "why a thing is the way it is",
    become: "",
    bed: "a thing that you sleep on in the night",
    bedroom: "a room in your home that you sleep in - a room with a bed in it",
    been: "how a thing was",
    before: "a time that was - you must have been before, but you can't be before again and you never will be before",
    began: "when a thing did become a thing for the first time is when it began",
    begin: "to make a thing a thing for the first time",
    behind: "",
    believe: "",
    bell: "",
    beside: "",
    besides: "",
    best: "when one of a thing is more good than every other one of that thing",
    better: "when one thing is more good than another thing",
    between: "a thing with one thing on one side and another thing on the other side is between them",
    big: "large - not small - when some of something is a long way a way from some other bit of that same thing",
    bit: "when you did bite someone in the past",
    bite: "to push on a thing with your top teeth and your bottom teeth - often so you can eat it",
    black: "the color that you have when you have no color - the color of the sky but with no night sky ball or star",
    blink: "to close both your left eye and right eye at the same time - often to make them a bit wet so they can work",
    block: "a large thing that is not round - or - to stop a person so they can't do the thing they want to do",
    blonde: "the color of some hair - a bit like the color of the sun",
    blood: "the red thing that is like water that is in your body to keep death away - when you lose more than a bit of this you should see a doctor",
    blue: "the color of the sky when it is bright - the color of water when there is a lot of it",
    blush: "",
    body: "the thing you are, or are in - your arm, your neck, your head, your leg, they are all a bit of this",
    book: "a box with many a word in it - it might help you know something, or it might be a fun story about a not real thing",
    bore: "",
    both: "a word for when you have one thing and you also have another thing - like and",
    bother: "",
    bottle: "",
    bottom: "the bit of a thing that is under the rest of it",
    box: "",
    boy: "a man who is young",
    boyfriend: "a boy (or young man) who is your friend - maybe who you go to bed with",
    brain: "the thing in your head that you use to think",
    break: "when you hit or cut a thing so that a bit of it is not with the rest of it anymore",
    breakfast: "food you eat at the start of the day",
    breath: "the air you pull and push out of your mouth to live",
    breathe: "when you push and pull air in and out of your body through your mouth, so that you can live",
    bright: "when there is a lot of light - the sun is bright, the night sky ball is less bright",
    bring: "take a thing to a place",
    broke: "when you had hit or cut a thing so that a bit of it is not with the rest of it anymore",
    broken: "when a thing is no what it should be - or when a thing that was one is now more than one",
    brother: "a man who has the same mum and dad as you",
    brought: "",
    brown: "the color of the world if you break the top off - or of shit",
    brush: "",
    build: "",
    burn: "set something on fire - make something so hot that it can stay hot on it's own - almost always will make smoke",
    burst: "when something is so full that it is cut into more than one piece by the stuff inside it",
    bus: "",
    business: "",
    busy: "when you have to do a lot in a small bit of time - maybe you have a lot of work to do, or a lot of people to talk to, in a small bit of time",
    but: "a word when you want to say one thing and another thing, and the second thing will make the first thing mean something weird",
    buy: "",
    by: "a word to say what or who did a thing - or - to move next to something",
    call: "yell or use a phone to talk to someone, maybe to ask them to come to where you are",
    calm: "",
    came: "",
    can: "when you are able to do a thing - or - a box you put food in that is very tight and hard",
    "can't": `short for "can not" (there's actually another way to make that short, but I can't write it with what I can use here)`,
    car: "",
    card: "",
    care: "",
    carefully: "",
    carry: "",
    case: "",
    cat: "an animal about as tall as your knee that has a long soft line from it's back, and four of a leg to stand on - more quiet and a bit more small than a dog",
    catch: "",
    caught: "",
    cause: "the thing that did make another thing be the way it is",
    cell: "",
    chair: "",
    chance: "",
    change: "",
    chase: "",
    check: "",
    cheek: "",
    chest: "the bit of your body that is under your neck - the bit that your heart is in - or - a big box you put stuff in",
    child: "a person who is not old - often if a man and a woman fuck, they can make a child",
    children: "more than one child",
    chuckle: "",
    city: "",
    class: "",
    clean: "to not have any not nice stuff stuck to you - or - to take the not nice stuff off something, often with water",
    clear: "",
    climb: "",
    close: "",
    clothes: "",
    coffee: "",
    cold: "",
    college: "",
    color: "how a thing can look - might be red or blue or green or grey",
    come: "",
    comment: "",
    complete: "",
    completely: "",
    computer: "",
    concern: "",
    confuse: "",
    consider: "",
    continue: "",
    control: "",
    conversation: "",
    cool: "",
    corner: "",
    couch: "",
    could: "when you were (or are) able to do something (but maybe you didn't)",
    "couldn't": `short for "could not"`,
    counter: "",
    couple: "two of something - or - two people who like each other a lot and stay together a lot",
    course: "",
    cover: "",
    crack: "",
    crazy: "",
    cross: "",
    crowd: "",
    cry: "",
    cup: "a round and deep thing that you can put water, or something like water, in - often, you drink from this",
    cut: "use a hard not wide thing (like a weird rock, or a broken bit of glass) to break a thing in a clean way - or - the break when a hard not wide thing has gone through a bit of something",
    cute: "",
    dad: "a man who has made a child",
    damn: "",
    dance: "",
    dark: "when it is not light - when it is hard to see anything",
    date: "",
    daughter: "a child you made who is a girl is your daughter",
    day: "",
    dead: "when a thing can not move or breathe or think or feel anymore - when a thing is not a live thing anymore",
    deal: "",
    dear: "",
    death: "not life - what will make a thing that is live, dead",
    decide: "",
    deep: "",
    definitely: "",
    desk: "",
    did: "",
    "didn't": `short for "did not"`,
    die: "",
    different: "not the same as something",
    dinner: "a thing you eat at the end of the day when it is almost dark",
    direction: "",
    disappear: "",
    do: "",
    doctor: "a person who can often make a sick person not sick - or, a person who should understand a lot because they did a lot of school",
    does: "",
    "doesn't": `short for "does not"`,
    dog: "an animal about as tall as your knee that has a long soft line from it's back, and four of a leg to stand on - more loud and strong than a cat",
    "don't": `short for "do not"`,
    done: "",
    door: "",
    doubt: "",
    down: "",
    drag: "",
    draw: "",
    dream: "",
    dress: "put a thing or two you wear on someone (often yourself) - or - a long and soft thing you can wear, often if you are a woman",
    drink: "put a thing like water in your body through your mouth so that you can live - or - a thing like water (often water) that you put in your body so you can live ",
    drive: "use a car or a bus to go from one place to another",
    drop: "",
    drove: "",
    dry: "make something not wet",
    during: "",
    each: "",
    ear: "",
    early: "",
    easily: "",
    easy: "",
    eat: "",
    edge: "",
    either: "",
    else: "",
    empty: "",
    end: "",
    enjoy: "",
    enough: "",
    enter: "",
    entire: "",
    escape: "",
    especially: "",
    even: "",
    evening: "",
    eventually: "",
    ever: "",
    every: "",
    everyone: "",
    everything: "",
    exactly: "",
    except: "",
    excite: "",
    exclaim: "",
    excuse: "",
    expect: "",
    explain: "",
    expression: "",
    eye: "a part of your body that you see out of - round and soft and in your head",
    eyebrow: "",
    face: "",
    fact: "",
    fall: "",
    family: "",
    far: "a place or thing that is a long way away from here - a place it will take a long time to get to",
    fast: "move from here to there in not much time",
    father: "",
    fault: "",
    favorite: "",
    fear: "",
    feel: "when you touch something and your brain does this",
    feet: "",
    fell: "",
    felt: "when you did feel something - or - the soft skin with hair you can get from some kind of animal",
    few: "more than one of something - less than a lot of something",
    field: "",
    fight: "",
    figure: "",
    fill: "",
    finally: "",
    find: "",
    fine: "very nice and very pretty - or - when you have to pay money because you did a bad thing",
    finger: "you have five of these on each hand - they are round and small and are made of three of a more small thing, except for the inside one which is made of two of a more small thing",
    finish: "",
    fire: "",
    first: "",
    fit: "",
    five: "",
    fix: "",
    flash: "",
    flip: "",
    floor: "",
    fly: "",
    focus: "",
    follow: "",
    food: "something you put in your mouth, break with your teeth, then pull into your body with your throat to live",
    foot: "there should be one of these at the bottom of each leg - they go forward and back so you can walk - they are long while you stand and can be a bit tall while you are in bed",
    for: "",
    force: "",
    forget: "",
    form: "",
    forward: "",
    found: "",
    four: "two and another two",
    free: "when you are able to do what you want to do - or - when you can take something with no money",
    friend: "a person you like to be with - you might go to their house or they might come to your house",
    from: "",
    front: "the side that the face of a person is on - or, the direction that the face of a person or thing is from them",
    frown: "when your mouth is sad and each end of it is under the middle of it",
    fuck: "when you and a person you love put your whole body together (often in bed) - or - a not nice word you say when you feel bad or sad (like shit)",
    full: "when a cup has all water and no air in it",
    fun: "",
    funny: "",
    further: "",
    game: "",
    gasp: "",
    gave: "",
    gaze: "look at something and don't look away",
    gently: "touch something in a very slow and not hard way - or, say something in a quiet and kind way",
    get: "",
    giggle: "",
    girl: "a woman who is young",
    girlfriend: "a woman you you like to spend time with (maybe in bed)",
    give: "",
    given: "",
    glad: "",
    glance: "",
    glare: "",
    glass: "",
    go: "",
    god: "",
    gone: "",
    gonna: "",
    good: "",
    got: "",
    gotten: "",
    grab: "",
    great: "",
    green: "",
    greet: "to say to someone that you are glad to be with them now",
    grey: "a sort of color that is a bit of every color, but they make each other not color - the color of a dark soft sky rain cup",
    grin: "when your mouth is happy and each end of it is above the middle of it - like smile, but often when something is funny",
    grip: "",
    groan: "",
    ground: "",
    group: "more than one of a thing, together",
    grow: "",
    guard: "a person who will try to keep something safe - or - to try to keep something safe",
    guess: "when you try to answer a question, but you are not sure that your answer is right",
    gun: "",
    guy: "a man",
    had: "",
    "hadn't": `short for "had not"`,
    hair: "",
    half: "",
    hall: "",
    hallway: "",
    hand: "",
    handle: "",
    hang: "",
    happen: "",
    happy: "",
    hard: "",
    has: "",
    hate: "",
    have: "",
    "haven't": `short for "have not"`,
    he: "",
    "he'd": `short for "he would" or "he had"`,
    "he's": `short for "he is"`,
    head: "the round thing on top of your neck - what your brain is in and your mouth is on",
    hear: "when there is a sound and you feel it",
    heard: "when you did hear something",
    heart: "",
    heavy: "",
    held: "",
    hell: "",
    hello: "a word you use to greet someone",
    help: "",
    her: "",
    here: "the place you are in now - the part of the world that you are in",
    herself: "",
    hey: "",
    hi: "",
    hide: "",
    high: "",
    him: "",
    himself: "",
    his: "",
    hit: "",
    hold: "",
    home: "where you live, often with the person you love in bed, or your father or mother or child - might be an apartment or a house - will often have a bedroom, a bathroom, and so on in it",
    hope: "",
    horse: "",
    hospital: "a place where many a doctor is - a place for many a sick person to go to to try and get not sick",
    hot: "",
    hour: "",
    house: "a type of home - a place that has a wall on each side",
    how: "",
    however: "",
    hug: "to hold someone with your arm to say you love them",
    huge: "very large",
    huh: "",
    human: "",
    hundred: "a number - ten of ten",
    hung: "",
    hurry: "",
    hurt: "",
    i: "",
    "i'd": `short for "I had" or "I should" or "I would"`,
    "i'll": `short for "I will"`,
    "i'm": `short for "I am"`,
    "i've": `short for "I have"`,
    ice: "",
    idea: "",
    if: "",
    ignore: "",
    imagine: "",
    immediately: "",
    important: "",
    in: "",
    inside: "",
    instead: "",
    interest: "",
    interrupt: "",
    into: "",
    is: "",
    "isn't": `short for "is not"`,
    it: "",
    "it's": `short for "it is" or "it has" (not the same as "its")`,
    its: "",
    jacket: "",
    jeans: "",
    jerk: "",
    job: "",
    join: "",
    joke: "when you say a word or so that is funny - often will make a person laugh",
    jump: "",
    just: "",
    keep: "",
    kept: "",
    key: "a small thing you hold and put in a door to open it",
    kick: "use your foot to push something (maybe a ball) hard and fast",
    kid: "a person who is not old - or - to say something that is a joke",
    kill: "make an animal not live",
    kind: "",
    kiss: "touch your mouth against a bit of the body of another person (maybe their mouth) to say you love them",
    kitchen: "a room in a house that you use to make food",
    knee: "",
    knew: "",
    knock: "",
    know: "",
    known: "",
    lady: "",
    land: "",
    large: "big - there is more of a large thing than there is of a small thing",
    last: "",
    late: "",
    laugh: "breathe out in a way that will make noise, because you are happy or because something was funny",
    lay: "",
    lead: "",
    lean: "",
    learn: "",
    least: "",
    leave: "",
    led: "",
    left: "",
    leg: "there should be two of these in the bottom half of you - they go forward and back so you can walk - they are tall while you stand and are long while you are in bed",
    less: "",
    let: "",
    letter: "",
    lie: "",
    life: "",
    lift: "",
    light: "a very tiny very very fast thing that can hit something and go into your eye to let you see it - or - when it easy to see everything (or hard because there it is so easy to see that you have to close your eye)",
    like: "",
    line: "",
    lip: "",
    listen: "",
    little: "",
    live: "",
    lock: "",
    locker: "",
    long: "",
    look: "",
    lose: "",
    lost: "",
    lot: "",
    loud: "",
    love: "",
    low: "",
    lunch: "when you eat food in the middle of the day",
    mad: "",
    made: "",
    make: "",
    man: "a type of human that often has short hair and often does not have a round chest",
    manage: "",
    many: "",
    mark: "",
    marry: "",
    match: "",
    matter: "",
    may: "",
    maybe: "",
    me: "",
    mean: "",
    meant: "",
    meet: "",
    memory: "",
    men: "",
    mention: "",
    met: "",
    middle: "",
    might: "",
    mind: "",
    mine: "",
    minute: "",
    mirror: "",
    miss: "",
    mom: "",
    moment: "",
    money: "",
    month: "",
    mood: "",
    more: "",
    morning: "",
    most: "",
    mother: "",
    mouth: "what you use to smile, or breathe, or eat - the thing in your head that you can open and close",
    move: "go from one spot to another - maybe fast or maybe slow",
    movie: "one picture after another after another so fast they seem to move",
    "mr.": "how you talk about a man when you are very nice and maybe do not know them very well",
    "mrs.": "how you talk about a woman when you are very nice and maybe do not know them very well",
    much: "",
    mum: "a woman who has made a child",
    mumble: "",
    music: "",
    must: "",
    mutter: "",
    my: "",
    myself: "",
    name: "",
    near: "",
    nearly: "",
    neck: "",
    need: "",
    nervous: "",
    never: "",
    new: "",
    next: "",
    nice: "",
    night: "the time when the sun is not in the sky and it is dark - often the less bright white ball is in the sky instead - often everyone is asleep",
    no: "",
    nod: "",
    noise: "",
    none: "",
    normal: "",
    nose: "",
    not: "",
    note: "",
    nothing: "no thing - without anything - an empty space, or not even the space",
    notice: "see something and pay attention to it",
    now: "the time it is as you read this",
    number: "",
    obviously: "",
    of: "",
    off: "",
    offer: "",
    office: "",
    often: "",
    oh: "",
    okay: "",
    old: "",
    on: "",
    once: "",
    one: "",
    only: "",
    onto: "",
    open: "",
    or: "",
    order: "",
    other: "",
    our: "",
    out: "",
    outside: "",
    over: "",
    own: "",
    pack: "",
    pain: "",
    paint: "",
    pair: "",
    pants: "",
    paper: "",
    parents: "",
    park: "",
    part: "",
    party: "",
    pass: "",
    past: "",
    pause: "",
    pay: "",
    people: "",
    perfect: "",
    perhaps: "",
    person: "an animal that does live and can both think and feel",
    phone: "",
    pick: "",
    picture: "",
    piece: "",
    pink: "",
    piss: "",
    place: "",
    plan: "",
    play: "",
    please: "",
    pocket: "",
    point: "",
    police: "",
    pop: "",
    position: "",
    possible: "",
    power: "",
    practically: "",
    present: "",
    press: "push or pull more than one thing together",
    pretend: "",
    pretty: "",
    probably: "",
    problem: "something that is bad - something that can make you not able to do a thing you want to do",
    promise: "say that you will do a thing even if it is hard to do",
    pull: "bring a thing to you with a touch",
    punch: "make your hand a ball and use it to push something (maybe a face) hard and fast",
    push: "make a thing go away from you with a touch",
    put: "",
    question: "a word (or more than one word) that is said so that the person you talk to will tell you what you want to know",
    quick: "",
    quickly: "",
    quiet: "when there is no noise, or only a very little bit of noise",
    quietly: "when you do something in a way that does not make any noise",
    quite: "",
    race: "when a lot of people go as fast as they can and see who is the most fast",
    rain: "little water that will move down from the sky and make the ground not dry",
    raise: "",
    ran: "",
    rang: "",
    rather: "",
    reach: "",
    read: "",
    ready: "",
    real: "when something is",
    realize: "",
    really: "",
    reason: "",
    recognize: "when you see something (or someone) and know what (or who) it is",
    red: "the color of blood, or of the ball that can grow on a tree that we most often talk about",
    relationship: "when one person and another person do stuff together, they are in a relationship",
    relax: "to not do much because you want to feel happy",
    remain: "to stay in the same place, or to stay in the same way",
    remember: "when you think about a thing you did learn in the past",
    remind: "when you are made to remember a thing",
    repeat: "when you do a thing, and do the same thing again",
    reply: "when you are told a word or so by someone and you say a word or so back to them - like respond",
    respond: "when you are told a word or so by someone and you say a word or so back to them - like reply",
    rest: "",
    return: "",
    ride: "",
    right: "one side of you (the one that is not left) - or - the thing that is good, or the word or so that is the same as the thing it is about",
    ring: "",
    road: "",
    rock: "",
    roll: "",
    room: "",
    rose: "",
    round: "",
    rub: "",
    run: "",
    rush: "",
    sad: "",
    safe: "",
    said: "",
    same: "",
    sat: "",
    save: "",
    saw: "",
    say: "",
    scare: "",
    school: "",
    scream: "",
    search: "",
    seat: "",
    second: "",
    see: "",
    seem: "",
    seen: "",
    self: "",
    send: "",
    sense: "",
    sent: "",
    serious: "",
    seriously: "",
    set: "",
    settle: "",
    seven: "",
    several: "",
    shadow: "",
    shake: "",
    share: "",
    she: "",
    "she'd": `short for "she had" or "she would"`,
    "she's": `short for "she is" or "she has"`,
    shift: "",
    shirt: "",
    shit: "a brown and wet thing that you push from yourself - or - a not nice word you say when you feel bad or sad (like shit)",
    shock: "when you did not think something would happen but then it did - can feel like surprise but with more pain",
    shoe: "a soft thing you put on your foot to keep it away from the ground when you walk",
    shook: "",
    shop: "a place where you can buy a thing or so",
    short: "it is not very far from the bottom of a short thing to the top of a short thing",
    shot: "",
    should: "",
    shoulder: "the bit of your body where the arm should join with the rest of the body - you have one on your right and one on your left, above your arm and under your neck",
    "shouldn't": `short for "should not"`,
    shout: "say something in a very loud way, so everyone who is around can hear you",
    shove: "push someone or something",
    show: "",
    shower: "",
    shrug: "",
    shut: "",
    sick: "",
    side: "",
    sigh: "",
    sight: "",
    sign: "",
    silence: "",
    silent: "",
    simply: "",
    since: "",
    single: "",
    sir: "",
    sister: "a woman who has the same mum and dad as you",
    sit: "",
    situation: "",
    six: "",
    skin: "",
    sky: "",
    slam: "",
    sleep: "",
    slightly: "",
    slip: "",
    slow: "",
    slowly: "",
    small: "when every bit of something is close to every other bit of it - not tall and not wide - not big",
    smell: "",
    smile: "when your mouth is happy and each end of it is above the middle of it - like grin, but often when something is nice",
    smirk: "",
    smoke: "",
    snap: "",
    so: "",
    soft: "",
    softly: "",
    some: "",
    somehow: "",
    someone: "",
    something: "a thing of some sort - it could be any thing, maybe a thought or maybe a thing you can touch",
    sometimes: "",
    somewhere: "a place of some sort - it could be any place",
    son: "a child you made who is a boy is your son",
    song: "",
    soon: "",
    sorry: "",
    sort: "",
    sound: "",
    space: "",
    speak: "",
    spend: "",
    spent: "",
    spoke: "",
    spot: "",
    stair: "",
    stand: "",
    star: "",
    stare: "",
    start: "",
    state: "",
    stay: "",
    step: "",
    stick: "",
    still: "",
    stomach: "",
    stood: "",
    stop: "",
    store: "",
    story: "",
    straight: "",
    strange: "",
    street: "",
    strong: "",
    struggle: "",
    stuck: "",
    student: "",
    study: "",
    stuff: "",
    stupid: "",
    such: "",
    suck: "pull on with your mouth",
    sudden: "",
    suddenly: "",
    suggest: "",
    summer: "",
    sun: "the big bright ball that is the cause of light in the day - it does a run up and down the sky once a day",
    suppose: "",
    sure: "when you know that a thing is some way",
    surprise: "when you did not think something would happen but then it did - can feel like shock but more soft",
    surround: "be on every side of something",
    sweet: "what you feel in your mouth when you bite a round red ball that can grow from a tree - or when eat an after dinner little bite",
    table: "a wide thing that, about half as tall as you, that does not live - you can eat food from it or write on top of it, and can put a cup on it",
    take: "get a thing that was mine and make it your thing",
    taken: "when a thing that was mine was got by you it was taken",
    talk: "when you say a word or so out loud so other people can hear and know what you want them to understand",
    tall: "from the bottom of a tall thing to the top of a tall thing is a long way",
    teacher: "a person who can tell other people about a thing or to - someone who can help other people understand a lot of stuff",
    team: "a group of people who try to do something together - they might work together or race together",
    tear: "when you pull a thing in more than one direction to break it into more than one piece",
    teeth: "you should have a lot of them in your mouth - white and hard and maybe straight",
    tell: "talk to someone about something",
    ten: "the number of word in this word group is ten",
    than: "",
    thank: "tell someone you are happy because of what they did",
    that: "",
    "that's": `short for "that is"`,
    the: "put this in front of a word to talk about just one of something (when you know which one of that thing)",
    their: "",
    them: "two or more people that are not you or me - or - a person, if you do not want to call them a him or a her",
    themselves: "",
    then: "a time that was before now",
    there: "a word for a place that is somewhere you are not - or - a word to say that something is",
    "there's": `short for "there is"`,
    these: "",
    they: "two or more people (or more than one thing) that is not you or me - or - a person, if you do not want to call them a him or a her",
    "they'd": `short for "they did" or "they had"`,
    "they're": `short for "they are"`,
    thick: "",
    thing: "one of anything - often something you can touch - might be a ball, or a dog, or a cup, or a sun",
    think: "say word after word in your head - try and figure out something in your head",
    third: "the thing after the thing after the first thing - the thing after the second thing",
    this: "put this in front of a word to talk about just one of something (when you know which one of that thing and you are right at it)",
    those: "",
    though: "",
    thought: "",
    three: "one thing, and one more thing, and one more thing, but no more than that",
    threw: "when you had done a throw before",
    throat: "the thing above your body, under your head, and inside your neck - air will go through this when you breathe",
    through: "",
    throw: "use your arm to push something",
    tie: "wrap a soft and long thing so that it is stuck to it - or - a long and not wide thing you tie above your jacket to look nice, often if you are a man",
    tight: "when one thing is close to another thing and all around it - maybe, when it is hard to take off your shirt, or hard to take off a bottle top",
    time: "",
    tiny: "very small - maybe hard to see because it is so small - maybe a hair or the small thing that air is made of",
    tire: "make someone want to be asleep",
    to: "",
    today: "the day it is now, if the sun is in the sky - tomorrow, it will be tomorrow, but for now it is today",
    together: "when one thing and another thing are close to each other - when there is not much between one thing and another thing",
    told: "when something was said in the past",
    tomorrow: "the day after today - the day it will be when the sun has been down and up again",
    tone: "the way a noise is - it might be bright or hard or high or low - a big car will often have a tone that is hard and low but a little animal that can fly will often have a tone that is high and bright",
    tongue: "",
    tonight: "the time it is now, if the sun is not in the sky - often, if you are in your bedroom it is tonight",
    too: "put this word after a thing and another thing when you want to say that they are both together",
    took: "when you have a thing that someone else had in the past, you took that thing",
    top: "the bit of a thing that is above everything else that is part of the thing (your hair is the top of your body)",
    totally: "",
    touch: "when one thing and another thing are next to each other with nothing between them they touch each other",
    toward: "when you move so that you become more close to me, you move toward me",
    town: "a lot more than one home all together",
    track: "a line on the ground that people can follow to get from one place to another - might be wide or not wide, might be made by a person or an animal - or - to follow someone or something",
    trail: "a line on the ground that people can follow to get from one place to another - like a track",
    train: "a big box made by people that can take many people from one place to another place - can only go on a long hard line next to another long hard line",
    tree: "a big brown tall thing with many of a little round not thick thing (often green) that grow off it",
    trip: "to go from one place to another place for a bit of time - or - when you walk, and then kick something and fall over a bit",
    trouble: "when there is a big chance that something bad will happen",
    trust: "when you think that someone will not break their promise",
    truth: "what is - when what is said is the same as what is",
    try: "when you want something to happen and you do a thing or two and hope that it will happen",
    turn: "when you point your body to where your left was before or where your right was before (or at least, a bit of the way there)",
    tv: "a box that can play a movie on it",
    twenty: "two of ten",
    two: "the number when you have one thing, and one other thing, but not any more than that",
    type: "",
    uncle: "the brother of your dad, or the brother of your mum",
    under: "",
    understand: "when you know what a thing is about - when you know what someone has in their brain",
    until: "",
    up: "away from the ground - on the way to the sky",
    upon: "",
    us: "you and me (if we are together), and maybe other people with us",
    use: "",
    usual: "",
    usually: "",
    very: "",
    visit: "go somewhere for a little bit of time",
    voice: "when you talk to someone, the noise you make from your mouth is your voice",
    wait: "stop what you do until the thing you expect to happen does happen",
    wake: "do not sleep anymore - get out of bed and start to give attention to the world",
    walk: "move your left leg and then your right leg and then your left leg again to move your body slowly",
    wall: "",
    want: "",
    warm: "",
    warn: "tell someone that something bad is about to happen",
    was: "",
    "wasn't": `short for "was not"`,
    watch: "",
    water: "the thing that can make something wet - clear and not hard and often see through - you must drink this to live - even more important than breakfast",
    wave: "a wall of water (or air) that will move in a direction for a while - or - to move your hand from left to right and back to left again (and so on) to say hello to someone",
    way: "a trail from one place to another place - or - how a thing is",
    we: "you and me and maybe some other people",
    "we'll": `short for "we will"`,
    "we're": `short for "we are"`,
    "we've": `short for "we have"`,
    wear: "when you put a soft thing on your body to cover your body (or a bit of it)",
    week: "seven of a day",
    weird: "not normal - different to most of something",
    well: "to be not sick - or - when something is (or was) the way you would like to be",
    went: "to have gone somewhere or some way in the past",
    were: "the have been some place or some way in the past",
    "weren't": `short for "were not"`,
    wet: "when something has water on it and it is not as hard anymore, and maybe not as hot either",
    what: "",
    "what's": `short for "what is"`,
    whatever: "",
    when: "",
    where: "",
    whether: "",
    which: "",
    while: "",
    whisper: "say something in a very very quiet way, so your breath is almost as loud as your word",
    white: "the color of the bright night sky ball, and the color of the thing everyone can write on if they have a small stick with a dark thing like water in it",
    who: "",
    whole: "",
    why: "",
    wide: "",
    wife: "a woman you live with and should love very much - a woman you promise to go to bed with as long as you both live - a woman you fuck because you love each other",
    will: "",
    wind: "when air does move past the world - it can be cold or loud sometimes",
    window: "a thing you can look through to see the world outside when you are inside something",
    wipe: "push water or something like it gently off something else",
    wish: "ask for something to happen that you would like to happen",
    with: "when one thing and another thing are together, they are with each other",
    within: "inside - in between the left and the right and the top and the bottom of something",
    without: "outside - not within",
    woke: "when you made someone not asleep in the past",
    woman: "a type of human that often has long hair and a round chest",
    women: "a group of more than one woman",
    "won't": `short for "will not" (weird, isn't it)`,
    wonder: "to think about how a thing might be",
    wood: "the hard brown bit of a tree - you can use it to make a table, or a house, or something else",
    word: "a single bit of what you say or write that will still mean something when alone",
    wore: "",
    work: "what you do to get money, often from the morning until the afternoon",
    world: "everything around you except for the far away sky",
    worry: "",
    worse: "when one thing is not as good as another thing it is worse",
    would: "",
    "wouldn't": `short for "would not"`,
    wow: "a sound you make when you fell surprise or shock",
    wrap: "",
    write: "",
    wrong: "when you say a word or so that is not the way that something is (that is, not right) - or, when you do something that is bad",
    yeah: `what you say when you think what was said is right, and you do not want to say "yes"`,
    year: "three of one hundred, six of ten, and five of one of a day - when the sun is quickly gone, slowly gone, and quickly gone again - when the world has gone around the sun once",
    yell: "say something very loud, maybe because you're angry - like scream but you may not feel fear and it may be a real word",
    yes: "what you say when you think what was said is right",
    yet: "",
    you: "the person who can see from your eye and feel from your hand - the person who right now can understand this word - the person who has the same mum and dad as you who is not your brother or sister - should be one of the people who is most often in your house",
    "you'd": `short for "you would"`,
    "you'll": `short for "you will"`,
    "you're": `short for "you are"`,
    "you've": `short for "you have"`,
    young: "when someone or something has not felt many of a year",
    your: "",
    yourself: "",
}